In [1]:
conda install -n base ipykernel --update-deps --force-reinstall

Collecting package metadata (current_repodata.json): ...working... done

Note: you may need to restart the kernel to use updated packages.Solving environment: ...working... Solving environment: ...working...

Updating parso is constricted by

==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3

anaconda -> requires parso==0.7.0=py_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating jupyter_core is constricted by

anaconda -> requires jupyter_core==4.6.3=py38_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating certifi is constricted by

anaconda -> requires certifi==2020.6.20=py38_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating colorama is constricted by

anaconda -> requires colorama==0.4.3=py_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating zlib is constricted by

anaconda -> requires zlib==1.2.11=h62dcd97_4

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating vs2015_runtime is constricted by

anaconda -> requires vs2015_runtime==14.16.27012=hf0eaf9b_3

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating pip is constricted by

anaconda -> requires pip==20.1.1=py38_1

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating wheel is constricted by

anaconda -> requires wheel==0.34.2=py38_0

  latest version: 26.1.1

Please update conda by running

    $ conda update -n base -c defaults conda

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating pyzmq is constricted by

anaconda -> requires pyzmq==19.0.1=py38ha925a31_1

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating jupyter_client is constricted by

anaconda -> requires jupyter_client==6.1.6=py_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating jedi is constricted by

anaconda -> requires jedi==0.17.1=py38_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating python-dateutil is constricted by

anaconda -> requires python-dateutil==2.8.1=py_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating sqlite is constricted by

anaconda -> requires sqlite==3.32.3=h2a8f88b_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating python is constricted by

anaconda -> requires python==3.8.3=he1778fa_2

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating traitlets is constricted by

anaconda -> requires traitlets==4.3.3=py38_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating decorator is constricted by

anaconda -> requires decorator==4.4.2=py_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating vc is constricted by

anaconda -> requires vc==14.1=h0510ff6_4

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating ca-certificates is constricted by

anaconda -> requires ca-certificates==2020.6.24=0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating zeromq is constricted by

anaconda -> requires zeromq==4.3.2=ha925a31_2

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating setuptools is constricted by

anaconda -> requires setuptools==49.2.0=py38_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating ipython is constricted by

anaconda -> requires ipython==7.16.1=py38h5ca1d4c_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating libsodium is constricted by

anaconda -> requires libsodium==1.0.18=h62dcd97_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating ipykernel is constricted by

anaconda -> requires ipykernel==5.3.2=py38h5ca1d4c_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating prompt-toolkit is constricted by

anaconda -> requires prompt-toolkit==3.0.5=py_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating openssl is constricted by

anaconda -> requires openssl==1.1.1g=he774522_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating tornado is constricted by

anaconda -> requires tornado==6.0.4=py38he774522_1

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating six is constricted by

anaconda -> requires six==1.15.0=py_0

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`



Updating pywin32 is constricted by

anaconda -> requires pywin32==227=py38he774522_1

If you are sure you want an update of your package either try `conda update --all` or install a specific version of the package you want using `conda install <pkg>=<version>`

done
done

## Package Plan ##

  environment location: C:\Users\parig\anaconda3

  added / updated specs:
    - backcall
    - ca-certificates
    - certifi
    - colorama
    - decorator
    - ipykernel
    - ipython
    - ipython_genutils
    - jedi
    - jupyter_client
    - jupyter_core
    - libsodium
    - openssl
    - parso
    - pickleshare
    - pip
    - prompt-toolkit
    - pygments
    - python-dateutil
    - python=3.8
    - pywin32
    - pyzmq
    - setuptools
    - six
    - sqlite
    - tornado
    - traitlets
    - vc
    - vs2015_runtime
    - wcwidth
    - wheel
    - wincertstore
    - zeromq
    - zlib



Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done

In [3]:
from pandas.core.computation.check import NUMEXPR_INSTALLED

In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

In [13]:
import glob

path = r"C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution*.dat"

files = glob.glob(path)

df_list = []

for f in files:
    temp = pd.read_csv(f, sep="\t", header=None)
    df_list.append(temp)

data = pd.concat(df_list, ignore_index=True)

expression = data.iloc[:,2:]

print("Total states:", expression.shape)

expression_clean = expression.dropna()

print("After removing NaN:", expression_clean.shape)

Total states: (35834, 310)
After removing NaN: (2, 310)

361 rows → steady states (models × states)
155 columns → variables

In [14]:
expression_clean.head()

,2,3,4,5,6,7,8,9,10,11,...,302,303,304,305,306,307,308,309,310,311
25946,5.120619,-24.940928,0.667091,16.688579,-3.605961,-21.365400,7.509020,-11.424763,-13.196197,-15.522708,...,7.121538,5.794405,7.488850,-1.499463,4.261317,-3.493215,0.532519,8.139607,4.868787,5.268372
25947,6.611202,-27.711711,-4.768529,21.226068,-9.476496,-17.920288,7.325985,-14.666465,-13.179634,-17.675838,...,-1.202068,6.735833,6.674503,8.160101,-3.216721,0.336821,0.335483,7.261438,2.899176,5.947265

In [15]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,302,303,304,305,306,307,308,309,310,311
0,1,3,63.0,7.108121,-48.653833,-4.020468,19.827913,-13.516745,-9.331465,9.201911,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,3,25.0,-12.862042,19.532225,6.360819,-34.684565,3.892671,8.863727,-8.726117,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,3,12.0,-12.862042,19.532225,6.360819,-34.684564,3.892671,8.863727,-8.732366,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,2,93.0,7.076730,-42.634940,-3.180281,21.573511,-7.654882,-15.091095,5.761209,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,2,7.0,-8.214471,15.913007,5.088166,-27.921087,4.232264,6.461941,-10.901555,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
data.shape

(35834, 312)

In [17]:
data.iloc[0]

0       1.000000
1       3.000000
2      63.000000
3       7.108121
4     -48.653833
         ...
307          NaN
308          NaN
309          NaN
310          NaN
311          NaN
Name: 0, Length: 312, dtype: float64

In [18]:
expression = data.iloc[:, 3:158]

print(expression.shape)

expression_clean = expression.dropna()

print("After removing NaN:", expression_clean.shape)

(35834, 155)
After removing NaN: (67, 155)

In [19]:
path = r"C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution*.dat"
files = glob.glob(path)

for f in files:
    d = pd.read_csv(f, sep="\t", header=None)
    expr = d.iloc[:,3:158]
    clean = expr.dropna()
    print(f, clean.shape)

C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution.dat (25834, 31)
C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution_1.dat (112, 30)
C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution_10.dat (2, 155)
C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution_2.dat (5324, 61)
C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution_3.dat (3601, 92)
C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution_4.dat (656, 123)
C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution_5.dat (240, 154)
C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution_6.dat (40, 155)
C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution_7.dat (16, 155)
C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution_8.dat (6, 155)
C:\Users\parig\OneDrive\Desktop\RACIPE_PROJECT\oggrn_solution_9.dat (3, 155)

This means:

👉 RACIPE ran correctly
👉 Multistability distribution printed earlier is correct

BUT

👉 Very few parameter sets converged fully

So:

Network is numerically very stiff
Large AML GRN → difficult dynamical system
Only ~0.18% steady states usable

This is not uncommon for very large GRNs

In RACIPE:

Valid steady state = full vector convergence
Partial convergence = not usable for phenotype analysis

So always:

“Use only fully converged steady states for downstream analysis.”

From topo file:

👉 Total nodes (TFs) = 31

This is a core AML regulatory network, NOT 155 genes.

Key regulators present:

MYC
TP53
RB1
E2F family
STAT3
DNMT1 / DNMT3A
RARA
PAX5
TFDP1
etc.

👉 This is biologically meaningful and perfect size for RACIPE.

⭐ Then Why Were You Seeing 155 Columns?

Because:

RACIPE output file had extra solver columns + padding
You accidentally selected too many columns earlier
True expression matrix = 31 genes